<!DOCTYPE html>
<html lang="en" class="js csstransforms3d">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="generator" content="Hugo 0.60.1" />
    <meta name="description" content="DS Bootcamp in R">
<meta name="author" content="Tatjana Kecojevic">

    <link rel="shortcut icon" href="/images/favicon.png" type="image/x-icon" />

    <title>M R var vs A E var :: DS Bootcamp in R</title>

    
    <link href="/css/nucleus.css?1582122462" rel="stylesheet">
    <link href="/css/fontawesome-all.min.css?1582122462" rel="stylesheet">
    <link href="/css/hybrid.css?1582122462" rel="stylesheet">
    <link href="/css/featherlight.min.css?1582122462" rel="stylesheet">
    <link href="/css/perfect-scrollbar.min.css?1582122462" rel="stylesheet">
    <link href="/css/auto-complete.css?1582122462" rel="stylesheet">
    <link href="/css/atom-one-dark-reasonable.css?1582122462" rel="stylesheet">
    <link href="/css/theme.css?1582122462" rel="stylesheet">
    <link href="/css/hugo-theme.css?1582122462" rel="stylesheet">
    

    <script src="/js/jquery-3.3.1.min.js?1582122462"></script>

    <style>
      :root #header + #content > #left > #rlblock_left{
          display:none !important;
      }
      
    </style>
    
  </head>
  <body class="" data-url="/module3/mva/">
    <nav id="sidebar" class="showVisitedLinks">



  <div id="header-wrapper">
    <div id="header">
      <!DOCTYPE html>
<html>
<body>
<IMG SRC="/images/logo.png" ALT="DataTeka" WIDTH=100 HEIGHT=100>

</body>
</html>


    </div>
    
        <div class="searchbox">
    <label for="search-by"><i class="fas fa-search"></i></label>
    <input data-search-input id="search-by" type="search" placeholder="Search...">
    <span data-search-clear=""><i class="fas fa-times"></i></span>
</div>

<script type="text/javascript" src="/js/lunr.min.js?1582122462"></script>
<script type="text/javascript" src="/js/auto-complete.js?1582122462"></script>
<script type="text/javascript">
    
        var baseurl = "\/";
    
</script>
<script type="text/javascript" src="/js/search.js?1582122462"></script>

    
  </div>

    <div class="highlightable">
    <ul class="topics">

        
          
          


 
  
    
    <li data-nav-id="/general/" title="About the course" class="dd-item 
        
        
        
        ">
      <a href="/general/">
          <b>1. </b>About the course
          
            <i class="fas fa-check read-icon"></i>
          
      </a>
      
      
        <ul>
          
          
            
          
          
          
        
          
            
            


 
  
    
    <li data-nav-id="/general/whatlearn/" title="General Overview" class="dd-item 
        
        
        
        ">
      <a href="/general/whatlearn/">
          General Overview
          
            <i class="fas fa-check read-icon"></i>
          
      </a>
      
              
    </li>
  
 

            
          
            
            


 
  
    
    <li data-nav-id="/general/instructor/" title="Meet the Instructor" class="dd-item 
        
        
        
        ">
      <a href="/general/instructor/">
          Meet the Instructor
          
            <i class="fas fa-check read-icon"></i>
          
      </a>
      
              
    </li>
  
 

            
          
            
            


 
  
    
    <li data-nav-id="/general/syllabus/" title="Indicative Syllabus" class="dd-item 
        
        
        
        ">
      <a href="/general/syllabus/">
          Indicative Syllabus
          
            <i class="fas fa-check read-icon"></i>
          
      </a>
      
              
    </li>
  
 

            
          
        
        </ul>
              
    </li>
  
 

          
          


 
  
    
    <li data-nav-id="/module1/" title="Module 1" class="dd-item 
        
        
        
        ">
      <a href="/module1/">
          <b>2. </b>Module 1
          
            <i class="fas fa-check read-icon"></i>
          
      </a>
      
      
        <ul>
          
          
            
          
          
          
        
          
            
            


 
  
    
    <li data-nav-id="/module1/whatisr/" title="What is R?" class="dd-item 
        
        
        
        ">
      <a href="/module1/whatisr/">
          What is R?
          
            <i class="fas fa-check read-icon"></i>
          
      </a>
      
              
    </li>
  
 

            
          
            
            


 
  
    
    <li data-nav-id="/module1/installr/" title="Install R/RStudio" class="dd-item 
        
        
        
        ">
      <a href="/module1/installr/">
          Install R
          
            <i class="fas fa-check read-icon"></i>
          
      </a>
      
              
    </li>
  
 

            
          
            
            


 
  
    
    <li data-nav-id="/module1/rstudioide/" title="RStudio IDE" class="dd-item 
        
        
        
        ">
      <a href="/module1/rstudioide/">
          RStudio IDE
          
            <i class="fas fa-check read-icon"></i>
          
      </a>
      
              
    </li>
  
 

            
          
            
            


 
  
    
    <li data-nav-id="/module1/user/" title="How to use R?" class="dd-item 
        
        
        
        ">
      <a href="/module1/user/">
          How to use R?
          
            <i class="fas fa-check read-icon"></i>
          
      </a>
      
              
    </li>
  
 

            
          
            
            


 
  
    
    <li data-nav-id="/module1/statsconcepts/" title="Basic Stats Concepts" class="dd-item 
        
        
        
        ">
      <a href="/module1/statsconcepts/">
          Basic Stats Concepts
          
            <i class="fas fa-check read-icon"></i>
          
      </a>
      
              
    </li>
  
 

            
          
            
            


 
  
    
    <li data-nav-id="/module1/datatypes/" title="Data Types" class="dd-item 
        
        
        
        ">
      <a href="/module1/datatypes/">
          Data Types
          
            <i class="fas fa-check read-icon"></i>
          
      </a>
      
              
    </li>
  
 

            
          
            
            


 
  
    
    <li data-nav-id="/module1/importexport/" title="Import Data to R" class="dd-item 
        
        
        
        ">
      <a href="/module1/importexport/">
          Import Data to R
          
            <i class="fas fa-check read-icon"></i>
          
      </a>
      
              
    </li>
  
 

            
          
            
            


 
  
    
    <li data-nav-id="/module1/rmarkdown/" title="Reproducibility" class="dd-item 
        
        
        
        ">
      <a href="/module1/rmarkdown/">
          Reproducibility
          
            <i class="fas fa-check read-icon"></i>
          
      </a>
      
              
    </li>
  
 

            
          
        
        </ul>
              
    </li>
  
 

          
          


 
  
    
    <li data-nav-id="/module2/" title="Module 2" class="dd-item 
        
        
        
        ">
      <a href="/module2/">
          <b>3. </b>Module 2
          
            <i class="fas fa-check read-icon"></i>
          
      </a>
      
      
        <ul>
          
          
            
          
          
          
        
          
            
            


 
  
    
    <li data-nav-id="/module2/datawrangling/" title="Data Wrangling" class="dd-item 
        
        
        
        ">
      <a href="/module2/datawrangling/">
          Data Wrangling
          
            <i class="fas fa-check read-icon"></i>
          
      </a>
      
              
    </li>
  
 

            
          
            
            


 
  
    
    <li data-nav-id="/module2/principlesvisualisation/" title="Principles of Visualisation" class="dd-item 
        
        
        
        ">
      <a href="/module2/principlesvisualisation/">
          Principles of Visualisation
          
            <i class="fas fa-check read-icon"></i>
          
      </a>
      
              
    </li>
  
 

            
          
            
            


 
  
    
    <li data-nav-id="/module2/visualisation/" title="Data Visualisation" class="dd-item 
        
        
        
        ">
      <a href="/module2/visualisation/">
          Data Visualisation
          
            <i class="fas fa-check read-icon"></i>
          
      </a>
      
              
    </li>
  
 

            
          
            
            


 
  
    
    <li data-nav-id="/module2/spatialda/" title="Spatial Data Analysis" class="dd-item 
        
        
        
        ">
      <a href="/module2/spatialda/">
          Spatial Data Analysis
          
            <i class="fas fa-check read-icon"></i>
          
      </a>
      
      
        <ul>
          
          
          
          
        
          
            
            


 
  
    
      <li data-nav-id="/module2/spatialda/images/mokrin/" title="" class="dd-item ">
        <a href="/module2/spatialda/images/mokrin/">
        
        <i class="fas fa-check read-icon"></i>
        </a>
    </li>
     
  
 

            
          
        
        </ul>
              
    </li>
  
 

            
          
        
        </ul>
              
    </li>
  
 

          
          


 
  
    
    <li data-nav-id="/module3/" title="Module 3" class="dd-item 
        parent
        
        
        ">
      <a href="/module3/">
          <b>3. </b>Module 3
          
            <i class="fas fa-check read-icon"></i>
          
      </a>
      
      
        <ul>
          
          
            
          
          
          
        
          
            
            


 
  
    
    <li data-nav-id="/module3/damethodology/" title="Data Analysis Methodology" class="dd-item 
        
        
        
        ">
      <a href="/module3/damethodology/">
          Data Analysis Methodology
          
            <i class="fas fa-check read-icon"></i>
          
      </a>
      
              
    </li>
  
 

            
          
            
            


 
  
    
    <li data-nav-id="/module3/mva/" title="M R var vs A E var" class="dd-item 
        parent
        active
        
        ">
      <a href="/module3/mva/">
          M R var vs A E var
          
            <i class="fas fa-check read-icon"></i>
          
      </a>
      
              
    </li>
  
 

            
          
            
            


 
  
    
    <li data-nav-id="/module3/visualisation/" title="Data Visualisation" class="dd-item 
        
        
        
        ">
      <a href="/module3/visualisation/">
          Data Visualisation
          
            <i class="fas fa-check read-icon"></i>
          
      </a>
      
              
    </li>
  
 

            
          
            
            


 
  
    
    <li data-nav-id="/module3/spatialda/" title="Spatial Data Analysis" class="dd-item 
        
        
        
        ">
      <a href="/module3/spatialda/">
          Spatial Data Analysis
          
            <i class="fas fa-check read-icon"></i>
          
      </a>
      
      
        <ul>
          
          
          
          
        
          
            
            


 
  
    
      <li data-nav-id="/module3/spatialda/images/mokrin/" title="" class="dd-item ">
        <a href="/module3/spatialda/images/mokrin/">
        
        <i class="fas fa-check read-icon"></i>
        </a>
    </li>
     
  
 

            
          
        
        </ul>
              
    </li>
  
 

            
          
        
        </ul>
              
    </li>
  
 

          
         
    </ul>

    
    
      <section id="shortcuts">
        <h3>More</h3>
        <ul>
          
              <li> 
                  <a class="padding" href="https://github.com/TanjaKec"><i class='fab fa-fw fa-github'></i>GitHub</a>
              </li>
          
        </ul>
      </section>
    

    
    <section id="prefooter">
      <hr/>
      <ul>
      
      
      
        <li><a class="padding" href="#" data-clear-history-toggle=""><i class="fas fa-history fa-fw"></i> Clear History</a></li>
      
      </ul>
    </section>
    
    <section id="footer">
      <center>
    
    <a class="github-button" href="https://github.com/matcornic/hugo-theme-learn/archive/master.zip" data-icon="octicon-cloud-download" aria-label="Download matcornic/hugo-theme-learn on GitHub">Download</a>

    
    <a class="github-button" href="https://github.com/matcornic/hugo-theme-learn" data-icon="octicon-star" data-show-count="true" aria-label="Star matcornic/hugo-theme-learn on GitHub">Star</a>

    
    <a class="github-button" href="https://github.com/matcornic/hugo-theme-learn/fork" data-icon="octicon-repo-forked" data-show-count="true" aria-label="Fork matcornic/hugo-theme-learn on GitHub">Fork</a>

    <p>Built with <a href="https://github.com/matcornic/hugo-theme-learn"><i class="fas fa-heart"></i></a> from <a href="https://getgrav.org">Grav</a> and <a href="https://gohugo.io/">Hugo</a></p>
</center>

<script async defer src="https://buttons.github.io/buttons.js"></script>

    </section>
  </div>
</nav>





        <section id="body">
        <div id="overlay"></div>
        <div class="padding highlightable">
              
              <div>
                <div id="top-bar">
                
                  
                  
                  
                  <div id="top-github-link">
                    <a class="github-link" title='Edit this page' href="https://github.com/matcornic/hugo-theme-learn/edit/master/exampleSite/content/module3/MvA/_index.en.html" target="blank">
                      <i class="fas fa-code-branch"></i>
                      <span id="top-github-link-text">Edit this page</span>
                    </a>
                  </div>
                  
                
                
                <div id="breadcrumbs" itemscope="" itemtype="http://data-vocabulary.org/Breadcrumb">
                    <span id="sidebar-toggle-span">
                        <a href="#" id="sidebar-toggle" data-sidebar-toggle="">
                          <i class="fas fa-bars"></i>
                        </a>
                    </span>
                  
                  <span id="toc-menu"><i class="fas fa-list-alt"></i></span>
                  
                  <span class="links">
                 
                 
                    
          
          
            
            
          
          
            
            
          
          
            <a href='/'>DS Bootcamp in R</a> > <a href='/module3/'>Module 3</a> > M R var vs A E var
          
         
          
         
          
        
                 
                  </span>
                </div>
                
                    <div class="progress">
    <div class="wrapper">

    </div>
</div>

                
              </div>
            </div>
            
        <div id="head-tags">
        
        </div>
        
        <div id="body-inner">
          
            <h1>
              
              M R var vs A E var
            </h1>
          

        




	


<p><strong>Measured Response Variable vs Attribute Explanatory Variable</strong></p>
<p>There are many cases to which this data analysis situation is applicable. For example, if you would like to investigate if there is a gender pay gup in an organisation or if a chemical engineer wants to compare the hardness of five blends of paint you would conduct MvsA DA to reach a conclusion.</p>
<p>The focus of investigation is the response variable for which we seek to descrbe its variability and its causes. We use the explanatory variable to explore if its behaviour influences the changes in the response variable, ie. does the responds variable responds to the changes in the explanatory variable? We seek to find out if the variability in the response variable can be explained by the explanatory variable.</p>
<p>As in this data analysis situation focal point of our attention is the measured response variable, we put our focus on to its distribution. Since we investigate influence on its behaviours caused by the change in the attribute explanatory variable we apply the following underlying concept:</p>
<blockquote>
<p>There is a relationship between a measured response and an attribute explanatory variable if the average value of the response is dependent on the level of the attribute explanatory variable.</p>
</blockquote>
<p>For the case of the measured response variable versis the attribute expplanatory variable with two levels (M vs A(2)), this can be illustrated graphically by plotting the statistical distribution of the response variable for the two attribute levels as below:</p>
<p><img src="/module1/StatsConcepts/images/MvAMethodology.png?width=40pc" /></p>
<p><strong>There is no link:</strong>
&gt; Given a measured response and an attribute explanatory variable with two levels, red (attribute level 1) &amp; blue (attribute level 2). If the statistical distribution of the response variable for attribute level 1 and attribute level 2 are exactly the same then the level of the attribute variable has no influence on the value response, there is no relationship.</p>
<p><strong>There is a link:</strong>
&gt; Given a measured response and an attribute explanatory variable with two levels, red (attribute level 1) &amp; blue (attribute level 2). If the statistical distribution of the response variable for attribute level 1 and attribute level 2 have different means then the level of the attribute variable does influence the response variable.</p>
<p><strong>Illustrative Example:</strong></p>
<ul>
<li><p><strong>Response Variable:</strong> Amount Spent on Clothes per month</p></li>
<li><p><strong>Attribute Explanatory Variable:</strong> Gender (Male/Female)</p></li>
</ul>
<p>If Males and Females <em>have the same</em> ‘spending on clothes’ <em>characteristics</em> then the average amounts spent monthly by Males and by Female should be <em>the same</em>.</p>
<p>If Male and Females <em>have different</em> ‘spending on clothes’ <em>characteristics</em> then the average amount spent monthly by Males and Female would be <em>different</em>.</p>
<p>The definition uses the concept of a statistical distribution and the idea that the total population can be split into two or more sub-populations according to the level of the attribute. (i.e. in the illustrative example a population of Males and a population of Females). Then comparing the distributions and asking are they the same (no relationship) or do they differ in the means (there is a relationship).</p>

<div class="notices note" ><p>It is sufficient to require equal means for no connection and unequal means for a connection irrespective of the shape/structure of the distributions.</p>
</div>

<hr />
<p><strong>Working wih sample data</strong></p>
<p>The concepts above provide a clear framework for analysis. Working with sample data, which by definition is imperfect information and subject to sampling error, makes working with sample data more problematical. The analyst need to ask the key question is the sample data providing evidence of a real connection or is it a consequence of sampling error?</p>
<p>The common data analysis methodology introduced in the previous section provides a well defined methodology for working with sample data.</p>
<p>The basic question to be answered is:
Is there a connection/link between the response variable and the explanatory variable?</p>

<div class="notices warning" ><p>This requires a definition of what is meant by connection/link.</p>
</div>

<blockquote>
<p>The Initial Data Analysis <strong>I.D.A.</strong> is a set of simple descriptive procedures that enable the data analyst to make one of three judgements:</p>
<ol style="list-style-type: lower-roman">
<li><p>There is clearly no link between the response variable and the explanatory variable.</p></li>
<li><p>There is clearly a link between the response variable and the explanatory variable.</p></li>
<li><p>The sample evidence is unclear using these simple descriptive methods that more advanced methods are required to resolve the issue. In which case Further Data Analysis (FDA) is required.</p></li>
</ol>
</blockquote>
<blockquote>
<p>The resulting conclusions from the further data analysis <strong>F.D.A.</strong> can be one of two options:</p>
<ol style="list-style-type: lower-alpha">
<li><p>The outcome of the analysis suggests that there is no connection/link/relationship between the response variable and the explanatory variable, and then the analysis is complete.</p></li>
<li><p>The outcome of the analysis suggests that the level of the explanatory variable influences on the response variable, (i.e. there is a connection/link/relationship), then to complete the analysis the nature of the connection needs to be described.</p></li>
</ol>
</blockquote>
<pre class="txt"><code>To complete the data analysis the analyst needs to know how to perform the following three stages:

 -  What is the Initial Data analysis and how to interpret it
 -  How to perform the further data analysis if required
 -  How to describe the nature of any connection discovered.</code></pre>
<hr />
<p><strong>The Initial Data Analysis</strong></p>
<p>In general the Initial Data Analysis consists of constructing the mean value and a boxplot of the response variable for each level of the Attribute explanatory variable. Given a data sample the problem is how to construct the required means and boxplots.</p>
<p><strong>Case Study: Share Price Study</strong></p>
<p>Statistical data are usually organised as tables. Each row of the table represents an observation, whilst a column represent a variable.</p>
<p>A business analyst is studying share prices of companies from three different business sectors. As part of the study a random sample (n=60) of companies was selected and the following data was collected:</p>
<table>
<thead>
<tr class="header">
<th><strong>Variable</strong></th>
<th><strong>Description</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Share_Price</strong></td>
<td>The market value of a company share</td>
</tr>
<tr class="even">
<td><strong>Profit</strong></td>
<td>The company annual profit</td>
</tr>
<tr class="odd">
<td><strong>RD</strong></td>
<td>Company annual spending on research and development</td>
</tr>
<tr class="even">
<td><strong>Turnover</strong></td>
<td>Company annual total revenue</td>
</tr>
<tr class="odd">
<td><strong>Competition</strong></td>
<td>A variable coded:</td>
</tr>
<tr class="even">
<td></td>
<td>- <strong>0</strong> if the company operates in a very competitive market</td>
</tr>
<tr class="odd">
<td></td>
<td>- <strong>1</strong> if the company has a great deal of monopoly power</td>
</tr>
<tr class="even">
<td><strong>Sector</strong></td>
<td>A variable coded:</td>
</tr>
<tr class="odd">
<td></td>
<td>- <strong>1</strong> if the company operates in the IT business sector</td>
</tr>
<tr class="even">
<td></td>
<td>- <strong>2</strong> if the company operates in the Finance business sector</td>
</tr>
<tr class="odd">
<td></td>
<td>- <strong>3</strong> if the company operates in the Pharmaceutical business sector</td>
</tr>
<tr class="even">
<td><strong>Type</strong></td>
<td>A variable coded:</td>
</tr>
<tr class="odd">
<td></td>
<td>- <strong>0</strong> if the company does business mainly in Europe</td>
</tr>
<tr class="even">
<td></td>
<td>- <strong>1</strong> if the company trades globally</td>
</tr>
</tbody>
</table>
<p>First, we need to access this data in R. We will start by creating a new project the ‘MvA_2’ within which we will keep all relevant scripts (.R), R-Markdown (.Rmd), data files and so on.</p>
<p>Go to <strong>File | New Project… | New Directory</strong> in the directory name box type in the suggested name of the project and tick the box <strong>open in new session</strong>. Click on the “<strong>Create Project</strong>” button. Open a new script ile:</p>
<p><img src="/module3/MvA/images/NewScript_MvsA.png?width=40pc" /></p>
<p>and start coding.</p>
<p>Open the data:</p>
<pre class="r"><code>suppressPackageStartupMessages(library(dplyr))
# read csv file
companyd &lt;- read.csv(&quot;https://tanjakec.github.io/mydata/SHARE_PRICE.csv&quot;, header=T)
# have a look at the first few raws and the summary of data
head(companyd)</code></pre>
<pre><code>##   Share_Price Profit    RD Turnover Competition Sector Type
## 1         880  161.3 152.6    320.9           1      3    0
## 2         862  170.5 118.3    306.3           1      3    0
## 3         850  140.7 110.6    279.5           1      3    0
## 4         840  115.7  87.2    193.2           1      3    0
## 5         838  107.9  75.1    182.4           1      3    0
## 6         825  138.8 116.2    265.2           1      3    1</code></pre>
<pre class="r"><code># When applied to an object of class data.frame, summary shows descriptive statistics (Mean, SD, etc.)
summary(companyd)</code></pre>
<pre><code>##   Share_Price        Profit             RD            Turnover    
##  Min.   :101.0   Min.   :  2.90   Min.   : 39.20   Min.   : 30.3  
##  1st Qu.:501.2   1st Qu.: 59.73   1st Qu.: 75.78   1st Qu.:112.3  
##  Median :598.5   Median : 88.85   Median : 90.60   Median :173.5  
##  Mean   :602.8   Mean   : 84.76   Mean   : 89.64   Mean   :170.2  
##  3rd Qu.:739.8   3rd Qu.:106.62   3rd Qu.:104.15   3rd Qu.:216.6  
##  Max.   :880.0   Max.   :170.50   Max.   :152.60   Max.   :323.3  
##   Competition      Sector       Type    
##  Min.   :0.0   Min.   :1   Min.   :0.0  
##  1st Qu.:0.0   1st Qu.:1   1st Qu.:0.0  
##  Median :0.5   Median :2   Median :0.5  
##  Mean   :0.5   Mean   :2   Mean   :0.5  
##  3rd Qu.:1.0   3rd Qu.:3   3rd Qu.:1.0  
##  Max.   :1.0   Max.   :3   Max.   :1.0</code></pre>
<pre class="r"><code>glimpse(companyd)</code></pre>
<pre><code>## Observations: 60
## Variables: 7
## $ Share_Price &lt;int&gt; 880, 862, 850, 840, 838, 825, 808, 806, 801, 799, 78…
## $ Profit      &lt;dbl&gt; 161.3, 170.5, 140.7, 115.7, 107.9, 138.8, 102.0, 102…
## $ RD          &lt;dbl&gt; 152.6, 118.3, 110.6, 87.2, 75.1, 116.2, 91.3, 100.4,…
## $ Turnover    &lt;dbl&gt; 320.9, 306.3, 279.5, 193.2, 182.4, 265.2, 212.0, 170…
## $ Competition &lt;int&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0…
## $ Sector      &lt;int&gt; 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2, 2, 3, 3, 3…
## $ Type        &lt;int&gt; 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1…</code></pre>

<div class="notices warning" ><p>Does everything seem okay? Can you notice a problem?</p>
</div>

<p>The problem is that the variables: ‘Comparison’, ‘Sector’ and ‘Type’ are attribute variables and Currently they have been recognised as integer type. To encode a measured variable as an attribute variable we can use function <code>as.factor(variable_name)</code>.</p>
<pre class="r"><code>companyd[, 5] &lt;- as.factor(companyd[, 5])
companyd[, 6] &lt;- as.factor(companyd[, 6])
companyd[, 7] &lt;- as.factor(companyd[, 7])
# command lines for scanning your dataset quickly
summary(companyd)</code></pre>
<pre><code>##   Share_Price        Profit             RD            Turnover    
##  Min.   :101.0   Min.   :  2.90   Min.   : 39.20   Min.   : 30.3  
##  1st Qu.:501.2   1st Qu.: 59.73   1st Qu.: 75.78   1st Qu.:112.3  
##  Median :598.5   Median : 88.85   Median : 90.60   Median :173.5  
##  Mean   :602.8   Mean   : 84.76   Mean   : 89.64   Mean   :170.2  
##  3rd Qu.:739.8   3rd Qu.:106.62   3rd Qu.:104.15   3rd Qu.:216.6  
##  Max.   :880.0   Max.   :170.50   Max.   :152.60   Max.   :323.3  
##  Competition Sector Type  
##  0:30        1:20   0:30  
##  1:30        2:20   1:30  
##              3:20         
##                           
##                           
## </code></pre>
<pre class="r"><code>glimpse(companyd)</code></pre>
<pre><code>## Observations: 60
## Variables: 7
## $ Share_Price &lt;int&gt; 880, 862, 850, 840, 838, 825, 808, 806, 801, 799, 78…
## $ Profit      &lt;dbl&gt; 161.3, 170.5, 140.7, 115.7, 107.9, 138.8, 102.0, 102…
## $ RD          &lt;dbl&gt; 152.6, 118.3, 110.6, 87.2, 75.1, 116.2, 91.3, 100.4,…
## $ Turnover    &lt;dbl&gt; 320.9, 306.3, 279.5, 193.2, 182.4, 265.2, 212.0, 170…
## $ Competition &lt;fct&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0…
## $ Sector      &lt;fct&gt; 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2, 2, 3, 3, 3…
## $ Type        &lt;fct&gt; 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1…</code></pre>

<div class="notices note" ><p>Note that the form of the value returned by <!-- raw HTML omitted -->summary<!-- raw HTML omitted --> depends on the class of its argument. The matrix and data frame methods return a matrix of class “table”, obtained by applying summary to each column and collating the results.</p>
</div>

<p>Let us start our Share Price data analysis by familiarising with data and chacking individual summary for measured variables.</p>
<pre class="r"><code>sapply(companyd[,1:4], summary)</code></pre>
<pre><code>##         Share_Price    Profit      RD Turnover
## Min.       101.0000   2.90000  39.200  30.3000
## 1st Qu.    501.2500  59.72500  75.775 112.3500
## Median     598.5000  88.85000  90.600 173.5000
## Mean       602.7833  84.76333  89.645 170.1567
## 3rd Qu.    739.7500 106.62500 104.150 216.6000
## Max.       880.0000 170.50000 152.600 323.3000</code></pre>
<pre class="r"><code># To focus on the center of the distributions for 
# the masured variables you can ask only
# for the rows showing mean and median to be displayed. 
sapply(companyd[,1:4], summary)[3:4, ]</code></pre>
<pre><code>##        Share_Price   Profit     RD Turnover
## Median    598.5000 88.85000 90.600 173.5000
## Mean      602.7833 84.76333 89.645 170.1567</code></pre>
<pre class="r"><code># To observe spread of the data we can use standard deviation and/or Inter Quartile Range
sapply(companyd[,1:4], sd) </code></pre>
<pre><code>## Share_Price      Profit          RD    Turnover 
##   177.28461    37.76443    24.13231    75.72712</code></pre>
<pre class="r"><code>sapply(companyd[,1:4], IQR)</code></pre>
<pre><code>## Share_Price      Profit          RD    Turnover 
##     238.500      46.900      28.375     104.250</code></pre>
<p>Let us explore the distributions of the variables visually using the appropriate graphs. As we have discussed in the previous sections, we usualy use piechart or a barplot if you like to graph an attribute variable.</p>
<pre class="r"><code>barplot(table(companyd[, 5]), xlab=&quot;Commpetition&quot;, ylab=&quot;frequency&quot;)</code></pre>
<p><img src="/module3/MvA/_index.en_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<pre class="r"><code>barplot(table(companyd[, 7]), xlab=&quot;Type&quot;, ylab=&quot;frequency&quot;)</code></pre>
<p><img src="/module3/MvA/_index.en_files/figure-html/unnamed-chunk-4-2.png" width="672" /></p>
<pre class="r"><code>pie(table(companyd[, 6]), labels=names(companyd$Sector), col=c(3, 7, 5), main=&quot;Sector&quot;) </code></pre>
<p><img src="/module3/MvA/_index.en_files/figure-html/unnamed-chunk-4-3.png" width="672" /></p>
<p>We have learnt that histogram is appropriate to graphically explore a measured variable.</p>
<pre class="r"><code>hist(companyd[, 1], xlab=&quot;Share Price&quot;, main=&quot;Histogram of Share Price&quot;, col=&quot;gray&quot;)</code></pre>
<p><img src="/module3/MvA/_index.en_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<p>To see the density smoothing of the histogram, on your histogram you will plot the probability density rather than the freqeuncy of the measured variable, over which you can superimpose kernel density smoothing line.</p>
<pre class="r"><code>hist(companyd[, 1], xlab=&quot;Share Price&quot;, main=&quot;Histogram of Share Price&quot;, col=&quot;gray&quot;, prob=T)
lines(density(companyd[, 1]), col=&quot;red&quot;)</code></pre>
<p><img src="/module3/MvA/_index.en_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<p>You can also have the kernel density smoothing as an the individual plot.</p>
<pre class="r"><code>par(mfrow=c(2, 2))  # splits the graph window into 2 rows and 2 columns
plot(density(companyd[,1]), main=&quot;Density Function of Share Price&quot;)
plot(density(companyd[,2]), main=&quot;Density Function of Profit&quot;)
plot(density(companyd[,3]), main=&quot;Density Function of R&amp;D&quot;)
plot(density(companyd[,4]), main=&quot;Density Function of Turnover&quot;)</code></pre>
<p><img src="/module3/MvA/_index.en_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<hr />
<p>Exploratory analysis of the individual variables is important part of DA process as a way to familiarise with data and identify any anomalies that may be contained within the individual variables. However, the most exciting part of Data Analysis is exploration of the possible relationships between the variables and statistical modelling that we use in this part of DA process.</p>
<p>The main focus in this study is <em>the study of share prices of companies from three different business sectors</em>, ultimately this will help us to identify the <strong>response</strong> variable for this study which is <strong>Share_Price</strong> that is a <strong>measured</strong> type. In this section we are learning how to investigate a possible relationship between measured response and attribute with two levels explanatory variable. In this study there are two attribute variables with two levels: <strong>Competition</strong> and <strong>Type</strong> and both of those attribute variable seem reasonable to use as explanatory variables.</p>
<p>We will start the investigation for the case: <strong>Share_Price</strong> vs <strong>Competition</strong>.</p>
<p>Using data analysis methodology for M v A(2)</p>
<p><img src="/module1/StatsConcepts/images/MvAMethodology.png?width=40pc" /></p>
<p>We first need to conduct the IDA. For this part of the analysis we need to obtain the descriptive statistics and their visualisations in terms of the boxplots.</p>
<p><em>Step 1:</em> Obtain the descriptive statistic of the response variable split down by each level of the attribute explanatory variable:</p>
<ul>
<li>Providing the average value, of ‘Share_Price’ for all the companies who operates in a very competitive market (code 0) and the average value of ‘Share_Price’ for all companies that have a great deal of monopoly power (code 1).</li>
</ul>
<pre class="r"><code>with(companyd, tapply(Share_Price, Competition, summary))</code></pre>
<pre><code>## $`0`
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   101.0   479.8   527.0   530.0   588.5   777.0 
## 
## $`1`
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   240.0   647.5   703.5   675.5   804.8   880.0</code></pre>
<pre class="r"><code>with(companyd, tapply(Share_Price, Competition, sd))</code></pre>
<pre><code>##        0        1 
## 149.3169 175.2078</code></pre>
<pre class="r"><code>with(companyd, tapply(Share_Price, Competition, IQR))   </code></pre>
<pre><code>##      0      1 
## 108.75 157.25</code></pre>
<p>Once we get the required statistics we need to interpret these descriptive statistics of the two sub-distributions in order to make a conclusion about their equality, i.e. similarity as we are working with sample data. In other words, based on the statistics obtained, we need to answer the following question: Are the sub-distributions the same or different?</p>

<div class="notices note" ><p>Descriptive statistics describes data – it summarises and organises all of the collected data into something manageable and simple to understand. Yet, it could be difficult to interpret, unless you are very in tune and familiar with the variables you are observing. If you already have some prior knowledge about the subject matter you will most likely know what to expect to see and the interpretation of the statistics would not be so troublesome. However, we can always convert those statistics to a visual form which is simpler to digest and understand.</p>
</div>

<p>Graphical visualisation of the two sub-dustributions might help to answer this question! The <strong>boxplots</strong> are the standard graphical method of displaying this sort of data. The <strong>boxplots</strong> enables both the difference in means relative to their spreads (variability) to be assessed.</p>
<pre class="r"><code>#par(mfrow=c(1,1))
boxplot(Share_Price ~ Competition, data = companyd, boxwex = 0.25, main=&quot;Share Price vs Competition&quot;, xlab =&quot;Share_Price&quot;, ylab =&quot;Competition&quot;, col=c(&quot;palegreen3&quot;, &quot;orchid3&quot;), horizontal=T) </code></pre>
<p><img src="/module3/MvA/_index.en_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<p>From the obtained descriptive statistics visualised by the Boxplots the means are 530.00 for the companies which operate in a very competitive market and 675.50 for the companies that have a great deal of monopoly power. The key question now is:</p>
<p>Is the difference between the two means (675.50 – 530.00 = 145.50) indicating a real difference or is this difference a difference that could have occurred by chance as a result of sampling error?</p>
<p>This is a complex question but by matching the means and the boxplots obtained in the analysis against the boxplots for the three possible model outcomes discussed earlier when talking about methodology used form MvA(2) a suitable decision can be made. For the example <code>Share_Price</code> vs <code>Competition</code> given above the analytical process is describe below:</p>
<p>By matching the boxplots against the three model outcomes illustrated in the data analysis methodology diagram, the absolute difference (as above of 145.50) has limited value in isolation because the interpretation depends also on the variability of the sample data. The variability of the sample data is measured in terms of the standard deviation, and represented in the boxplot as the inter-quartile range (IQR) as the width of the box. This graphical display the boxplot enables both the difference in means relative to their spreads (variability) to be assessed. If the two boxplots appear to be one of top of each other, then the difference is consistent with sampling error. If, however the difference is such that the boxplots appear to be well separated, then the difference is indicative of a real difference in means and suggests that a connection/relationship is present. The in-between situation is a matter of judgement but if the means are different, and the boxes of the boxplots overlap considerably then this is indicative of needing further data analysis.</p>
<p>From the sample evidence following Data Analysis Methodology we can draw a conclusion that the market value of a company share does depend on the competition within which company operates. Average share price for the companies which operate in a very competitive market is 530.00, while for those that are operationg with a great deal of monopoly power is 145.50 more.</p>
<p>The outcome of the IDA has led us to the above conclusion skipping the FDA stage.</p>
<p><img src="/module1/StatsConcepts/images/DAMethodology.png?width=40pc" /></p>
<p>We recognised that this common methodology has three stages:</p>
<ol style="list-style-type: decimal">
<li>The Initial Data Analysis</li>
<li>The Further Data Analysis</li>
<li>Describing the Relationship</li>
</ol>
<p>and that the Further Data Analysis stage may or may-not be required depending on the outcome of the ‘Initial Data Analysis’ at Stage 1. By conducting the analysis for <code>Share_Price</code> vs <code>Competition</code>, we have also realised that Stage 3 ‘Describing the Relationship’ is dependent upon establishing that a link exists between the response variable and the explanatory variable.</p>
<p>We will move further and learn how to conduct the Further Data Analysis required for this particular data analysis situation</p>
<hr />
<p><strong>Further Data Analysis</strong></p>
<p>If the Initial Data Analysis is inconclusive then ‘Further Data Analysis’ is required. This further data analysis seeks to answer the question:</p>
<blockquote>
<p>Does the sample evidence support the viewpoint that there is no connection between the response variable and the explanatory variable, or does it support the view that there is a link?</p>
</blockquote>
<p>The Further Data Analysis is procedure that enables a decision to be made, based on the sample evidence, as to one of
two outcomes:</p>
<ul>
<li>There is no relationship</li>
<li>There is a relationship</li>
</ul>
<p>These statistical procedures are called <strong>hypothesis tests</strong>, which essentially provide <strong>a decision rule for choosing between one of the two outcomes</strong> “There is no relationship” or “There is a relationship” based on the sample evidence.</p>
<p>This chapter we will discuss the mechanics of the application of the hypothesis test, and not attempt to discuss the underlying theory.</p>
<p>All hypothesis tests are carried out in four stages:</p>
<ul>
<li>Stage 1: Specifying the hypotheses.</li>
<li>Stage 2: Defining the test parameters and the decision rule.</li>
<li>Stage 3: Examining the sample evidence.</li>
<li>Stage 4: The conclusions.</li>
</ul>
<p>The data analysis situation Measured v Attribute requires two different hypotheses tests, one hypothesis test for the situation where the attribute explanatory variable has exactly two levels, and a different hypothesis test for the situation were the attribute explanatory variable has three or more levels.</p>
<hr />
<p><strong>HYPOTHESIS TEST: Measured Reponse v Attribute Explanatory Variable with exactly two levels</strong></p>
<p>In the section above we started to investigate does the explanatory variable <em>Competition</em> influence the response variable <em>Share_Price</em>? The implication being does market value of the companies share depend on the competitiveness of the market within which they operate. Based on the sample evidence we were able to draw a conclusion about the nature of this relationship by conducting only the IDA.</p>
<p>Let us suppose that the IDA was inconclusive and that FDA is needed in order to draw a conclusion about the relationship between the <em>Share_Price</em> and <em>Competition</em>.</p>
<p>For this data analysis situation (MvA(2)) the required further analysis is the <strong>Student’s t-test</strong>.</p>
<p>The four stages are:</p>
<ul>
<li><p><strong>Stage 1</strong>: Define the hypotheses:</p>
<ul>
<li>H0: µ1 = µ2</li>
<li>H1: µ1 ≠ µ2</li>
</ul></li>
<li><p><strong>Stage 2</strong>: Defining the test parameters and the decision rule.</p></li>
</ul>
<p>For ‘M vs A’ problem, what is required to help decide based on the sample evidence between the two options H0 &amp; H1 is a measure of the relative separation of the boxplots. This relative measure should consider the difference between the two means and the variability of the data for both levels of the attribute. This measure of the relative separation of the boxplots should take into account the means and the standard deviations of the two samples.</p>
<p>An agreed decision rule can be formulated that specifies that if this relative measure of the separation of the boxplots is greater than a threshold value then there is a connection otherwise there is no evidence to support as link.</p>
<p>Such a measure of the relative separation of the boxplots exists and is called the ‘Student’s t Ratio’. The value of the <strong>t-ratio</strong> calculated from the sample data is normally called <strong>t_calc</strong> to emphasis the fact that it is calculated from sample data.</p>
<blockquote>
<p>A decision rule can now be formulated using the <strong>t_calc</strong> value. The bigger the <strong>t_calc</strong> value the larger the separation between the boxplots and the more likely it is that there is a link between the response variable and the explanatory variable. The decision rule specifies the range of values that can take to be consistent with H0, i.e. no connection, if the <strong>t_calc</strong> is outside that range then the decision rule is specifying that the sample data is consistent with H1, namely with there being a connection.</p>
</blockquote>
<p>The problem is now how to specify the agreed limits. <a href="https://en.wikipedia.org/wiki/William_Sealy_Gosset">W. S Gossett (1876-1937)</a> who wrote under the pseudonym of “Student” proposed the t-ratio in a paper published in 1908. He also evaluated the statistical distribution of the t-ratio to enable these threshold values to be obtained. This test procedure is called a hypothesis test and the test described is commonly referred to as <strong>the student’s t-test</strong>.</p>
<p>The agreed procedure for setting up the decision rule uses the distribution of the t-ratio and splits the area under the distribution into the proportions 2½% - 95% - 2½% giving the threshold value called <strong>t_crit</strong>.</p>
<ul>
<li><p>If <strong>t_calc</strong> value is <strong>numerically between</strong> the range <strong>-t_crit &amp; +t_crit</strong> then the decision rule is flagging <strong>H0</strong>. Supporting the viewpoint that <strong>there is no relationship</strong>.</p></li>
<li><p>If <strong>t_calc</strong> value is <strong>numerically outside</strong> the range <strong>–t_crit &amp; +t_crit</strong> then the decision rule is flagging <strong>H1</strong>. Supporting the viewpoint that <strong>there is a relationship</strong>.</p></li>
</ul>
<p>The value <strong>t_crit</strong> depends upon the sample size, through a measure called <strong>Degrees of Freedom</strong> (<strong>df</strong>). The hypothesis test described above is called the student’s <strong>t-test</strong> and is <strong>a two tailed test using the 5% level of significance</strong>.</p>

<div class="notices info" ><p>Reference to the tables of the percentage points of the student’s t distribution will show that one of the tabulations is the two tailed test at the 5% level of significance. The value obtained from the statistical tables will be referred to as <!-- raw HTML omitted -->t_crit<!-- raw HTML omitted -->.</p>
</div>

<p><img src="/module3/MvA/images/t-test.png?width=40pc" /></p>
<p>As we now realise, this stage calculates two key pieces of information, the value of <strong>t_calc</strong> as calculated from the sample data and the degrees of freedom. The degrees of freedom are required to enable the numerical value of <strong>t_crit</strong> to be looked up in the statistical tables or simply in R using the <code>qt(alpha, df)</code> function.</p>
<ul>
<li><strong>Stage 3</strong>: Doing the calculations:</li>
</ul>
<p>In practice this means using the sample data to calculate two things:</p>
<blockquote>
<p>The numerical value of <strong>t_calc</strong> and the value of the degrees of freedom (<strong>df</strong>). This provides all the information to complete the test, the df figure enables the precise value of t_calc to be looked in the statistical tables or directly obtaine in R, once this value is known the conclusion results from applying mechanicallythe decision rule as seen above:</p>
<ul>
<li><p>If t_calc value is numerically between the range -t_crit &amp; +t_crit then the decision rule is flagging H0. There is no &gt; relationship.</p></li>
<li><p>If t_calc value is numerically outside the range -t_crit &amp; +t_crit then the decision rule is flagging H1.
There is a relationship.</p></li>
</ul>
</blockquote>
<ul>
<li><strong>Stage 4</strong>: The conclusions.</li>
</ul>
<p>This final stage requires a statement of the outcome in terms of the original problem specification.</p>
<hr />
<p><strong>FDA: <code>Share_Price vs Competition</code></strong></p>
<p>Let us obtain the output for t-test for <code>Share_Price vs Competition</code>.</p>
<pre class="r"><code>t.test(Share_Price~Competition, data=companyd)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  Share_Price by Competition
## t = -3.4619, df = 56.578, p-value = 0.001028
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -229.67541  -61.32459
## sample estimates:
## mean in group 0 mean in group 1 
##        530.0333        675.5333</code></pre>
<p>In the output abowe we can see the statistics for the model that has been fitted: Share_Price Vs Competition. For this sample the t_calc is -3.4619 (<code>t_calc=-3.46</code>) and the degrees of freedom are 56.578 (<code>df=56</code>). Those are the two numbers that we need from his output that would enable us to test the hypotheses.</p>
<p>In order to test the hypothesis we need to obtain the critical value of the student’s t-ratio for df=56, thus we want the t_crit. We use the qt(p, df) function in R, which stands for quantile of t distribution. Alternatively, you can use the statistical tables.</p>
<p>This is two-tailed test of 5 percent significant level (thus, p = 1 - 0.5 / 2), so the critical value of Student’s t is:</p>
<pre class="r"><code>qt(0.975, 56.578)</code></pre>
<pre><code>## [1] 2.002789</code></pre>
<p>This means that in order to reject the null hypothesis our test statistic needs to be bigger than <code>t_crit=2.00</code>, and hence conclude that there is a relationship between the two variables used in the analysis. <code>t_calc=-3.46 &lt; t_crit=2.00 =&gt; H1</code>, thus there is a relationship between the variables: Share_Price and Competition, hence DESCRIBE THE RELATIONSHIP!!!</p>
<hr />
<p><strong>YOUR TURN</strong> 👇</p>
<ol style="list-style-type: decimal">
<li>Go to the portals with open data (global: gapminder, national: office of national statistics, or local) and see if you can find data that is interesting for you to explore. Write down what interesting features you are expecting to see and suggest types of the visualistions that could be used to illustrate them.</li>
</ol>
<hr />
<p>© 2020 Tatjana Kecojevic</p>





<footer class=" footline" >
	
</footer>

        
        </div> 
        

      </div>

    <div id="navigation">
        
        
        
        
            
            
                
                    
                    
                
                

                    
                    
                        
                    
                    

                    
                        
            
            
                
                    
                        
                        
                    
                
                

                    
                    
                        
                    
                    

                    
                        
            
            
                
                    
                
                

                    
                    
                    

                    
            
        
                    
                        
            
            
                
                    
                
                

                    
                    
                    

                    
            
        
                    
                        
            
            
                
                    
                
                

                    
                    
                    

                    
            
        
                    
            
        
                    
                        
            
            
                
                    
                
                

                    
                    
                        
                    
                    

                    
                        
            
            
                
                    
                
                

                    
                    
                    

                    
            
        
                    
                        
            
            
                
                    
                
                

                    
                    
                    

                    
            
        
                    
                        
            
            
                
                    
                
                

                    
                    
                    

                    
            
        
                    
                        
            
            
                
                    
                
                

                    
                    
                    

                    
            
        
                    
                        
            
            
                
                    
                
                

                    
                    
                    

                    
            
        
                    
                        
            
            
                
                    
                
                

                    
                    
                    

                    
            
        
                    
                        
            
            
                
                    
                
                

                    
                    
                    

                    
            
        
                    
                        
            
            
                
                    
                
                

                    
                    
                    

                    
            
        
                    
            
        
                    
                        
            
            
                
                    
                
                

                    
                    
                        
                    
                    

                    
                        
            
            
                
                    
                
                

                    
                    
                    

                    
            
        
                    
                        
            
            
                
                    
                
                

                    
                    
                    

                    
            
        
                    
                        
            
            
                
                    
                
                

                    
                    
                    

                    
            
        
                    
                        
            
            
                
                    
                
                

                    
                    
                    

                    
                        
            
            
                
                    
                
                

                    
                    
                    

                    
            
        
                    
            
        
                    
            
        
                    
                        
            
            
                
                    
                    
                
                

                    
                    
                        
                    
                    

                    
                        
            
            
                
                    
                        
                        
                    
                
                

                    
                    
                    

                    
            
        
                    
                        
            
            
                
                    
                    
                
                

                    
                    
                    

                    
            
        
                    
                        
            
            
                
                    
                        
                        
                    
                
                

                    
                    
                    

                    
            
        
                    
                        
            
            
                
                    
                
                

                    
                    
                    

                    
                        
            
            
                
                    
                
                

                    
                    
                    

                    
            
        
                    
            
        
                    
            
        
                    
            
        
        
        


	 
	 
		
			<a class="nav nav-prev" href="/module3/damethodology/" title="Data Analysis Methodology"> <i class="fa fa-chevron-left"></i></a>
		
		
			<a class="nav nav-next" href="/module3/visualisation/" title="Data Visualisation" style="margin-right: 0px;"><i class="fa fa-chevron-right"></i></a>
		
	
    </div>

    </section>
    
    <div style="left: -1000px; overflow: scroll; position: absolute; top: -1000px; border: none; box-sizing: content-box; height: 200px; margin: 0px; padding: 0px; width: 200px;">
      <div style="border: none; box-sizing: content-box; height: 200px; margin: 0px; padding: 0px; width: 200px;"></div>
    </div>
    <script src="/js/clipboard.min.js?1582122462"></script>
    <script src="/js/perfect-scrollbar.min.js?1582122462"></script>
    <script src="/js/perfect-scrollbar.jquery.min.js?1582122462"></script>
    <script src="/js/jquery.sticky.js?1582122462"></script>
    <script src="/js/featherlight.min.js?1582122462"></script>
    <script src="/js/highlight.pack.js?1582122462"></script>
    <script>hljs.initHighlightingOnLoad();</script>
    <script src="/js/modernizr.custom-3.6.0.js?1582122462"></script>
    <script src="/js/learn.js?1582122462"></script>
    <script src="/js/hugo-learn.js?1582122462"></script>

    <link href="/mermaid/mermaid.css?1582122462" rel="stylesheet" />
    <script src="/mermaid/mermaid.js?1582122462"></script>
    <script>
        mermaid.initialize({ startOnLoad: true });
    </script>
    <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-105947713-1', 'auto');
  ga('send', 'pageview');

</script>
  </body>
</html>
